### DISCUSSION TITLE
Cannot get External-Secrets to work with AWS EKS and Secrets Manager

### DISCUSSION THREAD

**Discussion by udemy-darnone1** [external-secrets/kubernetes-external-secrets#529] [Q&A]
I set this up and and created a values.yaml to override the default values in the chart.  I created a k8s secret called aws-credentials with keys id and key for and IAM user that has admin rights.  I deployed the helm chart, created an AWS secret, and External secret following the documentation. The secret never gets created.  If I do a describe on the external secret object I see and error:

 Status:               ERROR, Missing credentials in config

My values file is as follows.  Looking for solution.

```yaml
env:
  AWS_REGION: us-east-2
  AWS_DEFAULT_REGION: us-east-2

# Create environment variables from existing k8s secrets
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key

serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::123456789101:role/secrets-role'
  name: webserver-service-account

securityContext:
  fsGroup: 65534
```

**Comment by Flydiverny** [comment]
So first of what type of authentication are you trying to use for AWS?
In the values it looks like you are trying to use both ENV injected credentials and IAM Roles for service account credentials.

(I took the liberty of deleting your comment, and editing the issue. As the comment contained 2 copies of your values, one with the AWS account id which you may or may not be concerned with posting)

**Comment by udemy-darnone1** [comment]
Thanks for modifying my post. So then it is either service accounts or AWS credentials but not both?  So I could really uses someone's input I started with just the service account but then I added the AWS credentials because the external secret status reports ERROR, Missing credentials in config. Logging into the deployment the I can see the credentials are properly set. If I change the serviceAccount.create to false and copy out the annotation and name the generation the Kubernetes yam complains with

Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 17: did not find expected key

If I uncomment the annotation and name then the serviceaccount yaml is not generated but the deployment still references the name of the service account.  serviceAccountName: {{ template "kubernetes-external-secrets.serviceAccountName" . }}
Commenting out the service account causes the deployment  pod to go status error. 

So I am at a loss.

**Comment by Flydiverny** [comment]
I'm not sure of the exact precedence order but I believe set environment variables will override any other credentials.

There must be a service account, either created, or referenced by name to an already existing service account.
If you do not have any special requirements, I recommend you leave the default `serviceAccount.create: true`, no need to override the name.

If you are trying to use IAM roles for service account then set the annotation, if you are trying to use env variables for credentials then leave the annotation out.

As listed here https://github.com/godaddy/kubernetes-external-secrets#aws-based-backends there is several different ways to provide authentication details for AWS backends. You can only use **one** at a time.

And yes most of the docs here could use some love to better present the information it contains :)

**Comment by udemy-darnone1** [comment]
Markus, 

Thanks for your reply. Set the annotation where - in the deployment or the service account?  And is a role really required in the external secret. So I let the generation define a service account with an annotation specifying a role that has access to retrieve the secret but external secret complained of no credentials. I am attaching the deployment yamls for your reference. in another comment. If you could point out where I have gone wrong that would be really, really great.

**Comment by udemy-darnone1** [comment]
This is what I get:

kubectl get externalsecrets.kubernetes-client.io hello-service 
NAME            LAST SYNC   STATUS                                 AGE

hello-service   0s          ERROR, Missing credentials in config   11s

**Reply by taragurung** [reply]
I am stuck in similar issues, Tried with IAM role get same issue, when using environment variable get some certification mis-match issues.

**Comment by udemy-darnone1** [comment]
Here are the yaml files I am deploying. Tar extracts into templates. Trust relationship and policy are also included along with values.yaml.  The only thing not included is the aws-creds secret. I am still getting reds error from the external secret.   I definitely appreciate your assistance.

[templates.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5460242/templates.zip)

**Comment by Flydiverny** [comment]
Assuming you have a role `arn:aws:iam::123456789101:role/webserver-secrets-role` which has the trust relationship set.
You should be able to 

Set the annotation on the service account refering to this role 
```yaml
serviceAccount:
  annotations: 
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::123456789101:role/webserver-secrets-role'
  name: webserver-service-account
```

Remove the secret envs, eg this section:
```yaml
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: key
```

in your external secret resource remove the 
```yaml
  roleArn: arn:aws:iam::123456789101:role/webserver-secrets-role
```

 `roleArn` on an external secret is used to specify additional credentials for that specific secret, it will be assumed by the first role. 

You should be able to confirm that the credentials are picked up by exec into the pod, AWS provides some examples here
https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

Hopefully that gets you further! I know there is some trouble getting up and running with IRSA, but it should work given all configuration is correct 😄

**Reply by abork-dolby** [reply]
Hey @Flydiverny I'm also in the process of setting up external secrets for our EKS cluster and I'm also trying to use IRSA for authentication. Here is what's confusing to me.

This IAM role that you are assigning to your service account  `webserver-secrets-role` is this the same service account that is used by  external secrets controller itself?

What I'm wondering is the right way to go to have external secrets controller with it's own service account which has IAM role assigned to it OR I should create service account/IAM role for each `SecretStore`. Like this for example:
```yaml
# secretstore-1
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789101:role/secretstore-1-role
  name: secretstore-1-serviceaccount
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-1
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: secretstore-1-serviceaccount
---
# secretstore-2
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789101:role/secretstore-2-role
  name: secretstore-2-serviceaccount
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: secretstore-2
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: secretstore-2-serviceaccount
```

**Reply by abork-dolby** [reply]
Ah, this is so annoying... Google is constantly directing me to `kubernetes-external-secrets`, I'm actually using new one `external-secrets`... Anyway, if you know....

**Reply by Flydiverny** [reply]
I am not a 100% certain here, but by this config those roles are used only when getting secrets from those individual stores. It gives you more granularity on how you manage access. Like you could have a secret store in one namespace with a role that only has access to /team/bananas/* and in another namespace be limited to another path.

So I think you can do whichever you prefer for your security needs. One IRSA setup for the external secrets controller would be easier, but anyone that can create an external secret would have indirect access to all secrets.

Hope that helps!

**Reply by Flydiverny** [reply]
https://external-secrets.io/v0.4.4/provider-aws-secrets-manager/ provides some examples for various setups :)

**Reply by abork-dolby** [reply]
Yeah, you are right... After few more tries I was able to get it to work service account per `SecretStore` 🙌

**Comment by darnone** [comment]
Markus,

I followed your instructions above and I think I am getting closer but I am still not quite there yet. Now I am able to create an external secret but the secret is not getting created with the role I am using. looking at the logs on the deployment pod, it seems that my role is not working correctly and the role being used to access secrets is the NodeInstanceRole instead of the role in the service account. I attached my policy to the NodeInstanceRole and the external secret generated the secret as advertised. So I need to figure out what is going on with my role. Code is attached along with a log snippet. I will keep you posted - that you for your assistance.
[templates.zip](https://github.com/godaddy/kubernetes-external-secrets/files/5469539/templates.zip)

**Comment by Flydiverny** [comment]
NodeInstanceRole is the last fallback in the credential chain. Its always a mystery to me why the IRSA credentials aren't picked up!
One issue is the file permissions for the token file that is mounted but that should be solved with

```yaml
securityContext:
  fsGroup: 65534
```

Best to verify the configuration works without KES first. So the trust relationship is known to be working.

**Reply by rfinner** [reply]
Please explain this fsGroup security context and where we need it. thanks!

**Comment by darnone** [comment]
I think I figured this out.  I keep destroying and recreating EKS clusters to keep costs down, but I was forgetting to recreate the IODC identity provider. Duh!  I do my best work thinking in the shower.  So this is now working in a us-east-2  1.18 EKS test cluster created from a CentOS 7 machine with kubectl 1.18.8 , aws 2.0.57, helm version 3.34, and eksctl  0.30.0.  I am going redeploy this cluster with a KMS key acticated.  Then I need to move this to our work cluster.  it is EKS 1.17 cluster from a WSL Ubuntu running on Windows10, kubectl 1.17.7, aws  2.0.38, helm 3.3.0, and eksctl 0.28.1 (although eksctl does not come into play). I will keep you posted.

**Comment by darnone** [comment]
Markus,
I got the secret to work again in my test cluster with KMS enabled and I was able to get this to work inmy work cluster. I wanted to really thank you for all of your help, assistance and patience.

David

**Reply by vkbera** [reply]
@darnone  Will it be possible to provide all the deployment file that worked for you. I am also facing similar issue .

**Reply by darnone** [reply]
This is what I am doing - first create a secret in Secrets Manager.
```
aws secretsmanager create-secret --region ${AWS_DEFAULT_REGION} \
      --name ${KES_TEST_SECRET}/credentials \
      --secret-string '{"username":"admin","password":"1234"}'
```
If you are testing this often you can remove the secret immediately with:
```
aws secretsmanager delete-secret \
      --secret-id ${KES_TEST_SECRET}/credentials \
      --force-delete-without-recovery
```

Enable the OIDC provider: if not already enable in your cluster
```
eksctl utils associate-iam-oidc-provider --cluster ${CLUSTER_NAME} --approve
```

I am using eksctl to create the OIDC IRSA because it generates a lot of stuff but the IRSA looks like the following:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Federated": "arn:aws:iam::${AWS_ACCOUNT_ID}:oidc-provider/oidc.eks.${AWS_DEFAULT_REGION}.amazonaws.com/id/${OIDC_ID}"
      },
      "Action": "sts:AssumeRoleWithWebIdentity",
      "Condition": {
        "StringEquals": {
          "oidc.eks.${AWS_DEFAULT_REGION}.amazonaws.com/id/${OIC_ID}:sub": "system:serviceaccount:${KES_NAMESPACE}:${KES_SERVICE_ACCOUNT_NAME}",
          "oidc.eks${AW_DEFAULT_REGION}.amazonaws.com/id/${OIDC_ID}:aud": "sts.amazonaws.com"
        }
      }
    }
  ]
}
```
The IRSA above has no policy as the roles for the secret will assume this role and carry along its own policies.  Since the Helm chart provides the service account eksctl is only creating the role.  If you choose to use eksctl, you cannot create a IRSA without a policy (a missing feature) so you will need  "no-op" policy that does nothing to plug that gap.  Refer to the EKS workshop for more info.

We are overriding very few variables in the  Helm chart.  I pass in a values file:
```
env:
  AWS_REGION: ${AWS_DEFAULT_REGION}
  AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}

  # Caution: setting this frequency may incur additional charges on AWS
  POLLER_INTERVAL_MILLISECONDS: ${KES_POLLING_INTERVAL} # Caution, setting this frequency may incur additional charges on some platforms

  # requires permitted and permitted-key-name in all namespaces
  ENFORCE_NAMESPACE_ANNOTATIONS: true # requires permitted and permitted-key-name in all namespaces

serviceAccount:
  annotations:
    "eks.amazonaws.com/role-arn": 'arn:aws:iam::${AWS_ACCOUNT_ID}:role/${KES_ROLE_NAME}'
  name: ${KES_SERVICE_ACCOUNT_NAME}

securityContext:
  fsGroup: 65534
```

This file is in an extra directory I create in the chart called files.  So deploy the helm chart as follows:
```
helm install ${KES_HELM_RELEASE} ../charts/kubernetes-external-secrets/ \
      --skip-crds -f ../charts/kubernetes-external-secrets/files/daves-values.yaml \
      -n ${KES_NAMESPACE} --create-namespace
```
Check the logs and the deloyment to make sure KES is connecting with AWS.

The secret will need a role:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
        "Effect": "Allow",
        "Principal": {
            "AWS": "arn:aws:iam::${AWS_ACCOUNT_ID}:role/${KES_ROLE_NAME}"
        },
        "Action": "sts:AssumeRole"
        }
    ]
}
```

and a policy:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "KESPermissions",
            "Effect": "Allow",
            "Action": [
                "secretsmanager:GetResourcePolicy",
                "secretsmanager:GetSecretValue",
                "secretsmanager:DescribeSecret",
                "secretsmanager:ListSecretVersionIds"
            ],
            "Resource": [
                "arn:aws:secretsmanager:us-east-1:${AWS_ACCOUNT_ID}:secret:${KES_TEST_SECRET}"
            ]
        }
    ]
}
```

The secret deployment consists of a namespace that is annotated:
```
apiVersion: v1
kind: Namespace
metadata:
  name: ${KES_TEST_SECRET}-namespace
  # annotation permitted is configurable regular expresssion to match
  # the role or roles that are permitted to be used by pods in this
  # namespace
  
  annotations:
    # annotation iam.amazonaws.com/permitted is takes a configurable
    # regular expresssion that limites the range of roles that can
    # be assumed by resources in this namespace.
    iam.amazonaws.com/permitted: "arn:aws:iam::${AWS_ACCOUNT_ID}:role/.*${TEST_SECRET_ROLE}"
    # annotation externalsecrets.kubernetes-client.io/permitted-key-name
    # takes a configurable regular expresssion to limit the secrets that
    # can be acessed by resources in this namespace.
    # namespace, ie defender/credentials.
    externalsecrets.kubernetes-client.io/permitted-key-name: "${KES_TEST_SECRET}/.*"
spec: {}
status: {}
```
 
and the external secret itself:
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ${KES_TEST_SECRET}
  namespace: "${KES_TEST_SECRET}-namespace"
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${TEST_SECRET_ROLE}
  # optional: specify region
  region: ${AWS_DEFAULT_REGION}
  data:
    - key: ${KES_TEST_SECRET}/credentials
      name: password
      property: password
    - key: ${KES_TEST_SECRET}/credentials
      name: username
      property: username
```
There is a strange variable in the above that is from my automation. the TEST_SECRET-ROLE can be retrieved with:
```
export TEST_SECRET_ROLE=$(aws iam get-role --role-name ${KES_TEST_SECRET}-role | \
      jq .Role | grep RoleName | cut -d "\"" -f 4)
```
I believe it the same as ${KES_ROLE_NAME}

deploy the namespace and then deploy the external secret,  The secret should appear in the ${KES_TEST_SECRET}-namespace. I hope this helps.
