### DISCUSSION TITLE
no matches for kind "ExternalSecret" in version "kubernetes-client.io/v1"

### DISCUSSION THREAD

**Discussion by gangadharayya-hiremath-tm** [external-secrets/kubernetes-external-secrets#754] [General]
Hi All,

 Getting error "no matches for kind "ExternalSecret" in version "kubernetes-client.io/v1"" for the following manifest file, any clues will be helpful:

apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: test-secret
  namespace: dev
spec:
  backendType: secretsManager
  roleArn: arn:aws:iam::<<place holder aws account id>>:role/<<place holder role>>
  region: us-east-1
  data:
    - key: username
      name: tutorials/MyFirstTutorialSecret

**Comment by AppyDev** [comment]
@gangadharayya-hiremath-tm Any luck in finding a solution for the issue? I am facing the same issue

**Reply by gangadharayya-hiremath-tm** [reply]
Hi,

 We were able to overcome this issue by utilizing manifest as below

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test-secret
spec:
  backendType: secretsManager
  data:
  - key: tutorials/MyFirstTutorialSecret
    name: test-secret
```

We provided required IAM permission(as below) to K8S Secrets Manager via Service account:

```
{
      "Version": "2012-10-17",
      "Statement": [
          {
              "Effect": "Allow",
              "Action": [
                    "ssm:Describe*",
                    "ssm:Get*",
                    "ssm:List*",
                    "secretsmanager:GetResourcePolicy",
                    "secretsmanager:GetSecretValue",
                    "secretsmanager:DescribeSecret",
                    "secretsmanager:ListSecretVersionIds"
              ],
              "Resource": "*"
          }
      ]
  }
```
