### ISSUE TITLE
Add required IAM permissions to Readme

### ISSUE THREAD

**Issue by Sytten** [external-secrets/kubernetes-external-secrets#116]
It would be nice to tell us which permissions are required so we can limit the scope to the minimum.

**Comment by Flydiverny** [comment]
For reference this is the kind of policy document I've used:

Policy Document
```yaml
Version: 2012-10-17
Statement:
  - Effect: Allow
    Action: "kms:Decrypt"
    Resource: arn:aws:kms:eu-west-1:123456789:key/a0495691-1f7a-4d94-b27d-58a20e2d1aef

  - Effect: Allow
    Action:
      - "secretsmanager:GetSecretValue"
    Resource:
      - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:/development/*"
```

Granting access to decrypt using the keys which the secrets are encrypted with and granting access to a sub path of values ie all secrets with name starting with `/development/` in this case.
