### ISSUE TITLE
Return Error, null

### ISSUE THREAD

**Issue by debu99** [external-secrets/kubernetes-external-secrets#265]
If we use the below yaml and first key "/hello-service/password1" does not exist in AWS SSM, then ExternalSecret will stuck and return Error, null

The expected action should skip the one that not exist and continue with the next one

```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: systemManager
  data:
    - key: /hello-service/password1
      name: password1
    - key: /hello-service/password2
      name: password2
```
