### ISSUE TITLE
healthchecks?

### ISSUE THREAD

**Issue by dudicoco** [external-secrets/kubernetes-external-secrets#266]
Hi,

Is there a way to perform health checks on the controller using kubernetes probes?

Thanks

**Comment by timmyers** [comment]
Something a bit more built-in would be ideal, but the following is a reasonable strategy:

```yaml
livenessProbe:
  exec:
    command:
      - /bin/sh
      - -c
      - '! wget -q -O- localhost:3001/metrics | grep status=\"error\"'
  initialDelaySeconds: 30,
  periodSeconds: 30,
```

Checks the prometheus metrics to see if there have been any sync errors.

**Comment by aramse** [comment]
In my case the controller gets into a state where it stops reading ExternalSecret resources. Not sure more detail yet, but in the interim I'm trying the following to ensure it can still read them.

```YAML
livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - "cd ~ && wget -O es.json --no-check-certificate --header \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \"https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/apis/kubernetes-client.io/v1/namespaces/default/externalsecrets\""
  periodSeconds: 30
```

Even more comprehensive would be to create an ExternalSecret, and then confirm it's been created, though this would require more RBAC permissions than needed, less than ideal. There's really no escaping having to look through the logs/code on this one perhaps :)

**Comment by dudicoco** [comment]
Thanks @timmyers.
Would we want to restart the pod if there are sync errors? Doesn't seem like it's the right healthcheck to perform.

**Comment by timmyers** [comment]
It's definitely not ideal and I can think of cases it wouldn't be what you want.  For our set-up though, generally there are 0 sync errors unless something seems wrong with the pod and all of its communication is failing. A restart seems to fix it, so this might be better than no health check.

**Comment by aramse** [comment]
Agreed with @timmyers -- we also have syncing stop occurring without producing any errors in the logs, and a `kubectl rollout restart kubernetes-external-secrets` magically fixes it. I've tried the following and so far so good, but @timmyers's solution seems usable too, albeit both are of course less ideal than something more built-in. 

```YAML
livenessProbe:
  exec:
    command:
    - /bin/sh
    - -c
    - "cd ~ && wget -O es.json --no-check-certificate --header \"Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)\" \"https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_SERVICE_PORT/apis/kubernetes-client.io/v1/namespaces/default/externalsecrets\""
  periodSeconds: 30
```
