### ISSUE TITLE
IAM roles setup help

### ISSUE THREAD

**Issue by mo-saeed** [external-secrets/kubernetes-external-secrets#280]
Hi Guys,

Need your help how to install kubernetes-external-secrets on shared k8s cluster:

we have the following 
- 1 shared Kubernetes cluster
- project_A and project_B with 2 AWS accounts and 2 namespaces in the shared k8s cluster

How to achieve with one Kubernetes-external-secret installation that project_A's namespace has only access to AWSACCOUNT_A project_B's namespace has only access to AWSACCOUNT_B

I am using KIAM for Authentication.

Thanks

**Comment by mo-saeed** [comment]
@moolen May be you can help me here :)

**Comment by mo-saeed** [comment]
What I did is the following:
- Create IAM role in kubernetes cluster's AWS account called "ROLE_K8S" trusting kiam-server role.
- Create IAM role in the project A's AWS account called "ROLE_PROJ_A" with assume_role policy 
```
{
    "Version": "2012-10-17",
    "Statement": [{
        "Action": "sts:AssumeRole",
        "Principal": {
            "AWS": [
                "arn:aws:iam::K8S_ACCOUNT_ID:role/ROLE_K8S"
            ]
        },
        "Effect": "Allow"
    }]
}
```
and policy 
```
{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Action": [
      "secretsmanager:GetResourcePolicy",
      "secretsmanager:GetSecretValue",
      "secretsmanager:DescribeSecret",
      "secretsmanager:ListSecretVersionIds"
    ],
    "Resource": "*"
  }]
}
```
- Install kubernetes-external-secret with pod-annotation `iam.amazonaws.com/role: "arn:aws:iam::K8S_ACCOUNT_ID:role/ROLE_K8S"`
- apply this secret 
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-service
  namespace: test
spec:
  backendType: secretsManager
  #roleArn: "arn:aws:iam::PROJECT_A_ACCOUNT_ID:role/ROLE_PROJ_A"
  data:
    - key: hello-service/password
      name: password
  # optional: specify a template with any additional markup you would like added to the downstream Secret resource.
  # This template will be deep merged without mutating any existing fields. For example: you cannot override metadata.name.
  template:
    metadata:
      annotations:
        cat: cheese
      labels:
        dog: farfel
````
I got this error in the logs 
```
{"level":50,"time":1581433530865,"pid":17,"hostname":"k8s-asm-kubernetes-external-secrets-57679c594-dx8v7","message":"User: arn:aws:sts::K8S_ACCOUNT_ID:assumed-role/ROLE_K8S/kiam-kiam is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::PROJECT_A_ACCOUNT_ID:role/ROLE_PROJ_A"
```
I am not sure what I am doing wrong here and not sure if this is the right way to do it.
