### ISSUE TITLE
Enable secrets cache

### ISSUE THREAD

**Issue by shaikatz** [external-secrets/kubernetes-external-secrets#382]
Hello,

I would like to raise the idea of having a cache for polling the secrets.
My use case is having the same secret on multiple namespaces.

With the current implementation, the external secrets controller fetch AWS many times, one for each namespace, although they all use the same secrets manager entry.

Adding such a feature will reduce the API calls which will reduce cost.

**Comment by Flydiverny** [comment]
I think it's a good idea to have some kind of cache. Also if you do something like this:

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: secretsManager
  data:
    - key: hello-service/credentials
      name: username
      property: username
    - key: hello-service/credentials
      name: password
      property: password
```

It will fetch the `hello-service/credentials` secret twice which seems a bit unnecessary :)
It has to be properly implemented so it doesn't allow bypassing privileges.

It raises some questions of when to poll for changes? If we have two different secrets looking at the same secret, but they are created with 6 hours in between and the polling is every 12 hours. Will one have potentially 6 hour old data as it's a cache hit or how to deal with that.

It would require some refactoring though
