### ISSUE TITLE
External Secret From another Namespace

### ISSUE THREAD

**Issue by kferrone** [external-secrets/kubernetes-external-secrets#422]
Would be cool to have an external secret be created from another namespace or even another cluster. Would be simple too. One use case would be some service makes a secret in one namespace and another service wants to use it in another. Would also be nice to transform the keys too, sometimes generated key names in secrets are not so useful.

**Comment by Flydiverny** [comment]
@kferrone not sure what you refer to as generated key names? ExternalSecret resource allows you to specify any key name you want by setting the `name` property (which is required). Unless you are using `dataFrom` in which case I'd recommend using `data` if you want more control.

Would it not make more sense to have the other service create the external secret in the right place over having an externalsecret target another namespace? Seems like it could add abit of complexity and also potential naming conflicts, like what happens if two externalsecrets try to create a secret in the same place?

**Comment by kferrone** [comment]
What I meant to say is for ExternalSecret to have another backend called something like `kubernetes`. Then the GoDaddy ExternalSecret would copy a core Kubernetes secret from another namespace into the one it's in. When I say generated names I mean another service like the many Helm charts from [Bitnami](https://github.com/bitnami/charts/blob/master/bitnami/mysql/templates/secrets.yaml) and the [Stable](https://github.com/helm/charts/blob/master/stable/postgresql/templates/secrets.yaml) repo will often times include a secret which is controlled and named by the Helm chart. 

I imagine something like this:
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: mysql
  namespace: my-cool-app # this is the namespace I want it to be in
spec:
  backendType: kubernetes # a backend which is simply this cluster, or maybe even another 
  data:
    - key: /databases/mysql # databases is the namespace and mysql is a secret
      name: MYSQL_PASSWORD # here is what I want the name to be
      property: mysql-root-password # this is the name from the helm chart
```
