### ISSUE TITLE
Update docs for vault backend for KVv2 to clarifiy need of /data/ in secret key

### ISSUE THREAD

**Issue by DirtyCajunRice** [external-secrets/kubernetes-external-secrets#439]
I am on 4.2.0, and i get cannot get a v2 secret with 1 or 2 set for this. Both give the same error
```
{"level":50,"time":1594786938370,"pid":17,"hostname":"external-secrets-do-kubernetes-external-secrets-7bcb5d65fb4qdn4","response":{"statusCode":404,"body":{"request_id":"670b25b7-36ef-8888-d214-05a09271b72e","lease_id":"","renewable":false,"lease_duration":0,"data":null,"wrap_info":null,"warnings":["Invalid path for a versioned K/V secrets engine. See the API docs for the appropriate API endpoints to use. If using the Vault CLI, use 'vault kv get' for this operation."],"auth":null}},"stack":"Error: Status 404\n    at handleVaultResponse (/app/node_modules/node-vault/src/index.js:58:21)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)\n    at async VaultBackend._get (/app/lib/backends/vault-backend.js:55:28)\n    at async /app/lib/backends/kv-backend.js:29:31\n    at async Promise.all (index 1)\n    at async Promise.all (index 1)\n    at async VaultBackend.getSecretManifestData (/app/lib/backends/kv-backend.js:116:42)\n    at async Poller._createSecretManifest (/app/lib/poller.js:88:18)\n    at async Poller._upsertKubernetesSecret (/app/lib/poller.js:152:28)","type":"Error","msg":"failure while polling the secret cajun-pro/test-external-secret"}
```
es config:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: test-external-secret
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets
  kvVersion: 2
  data:
  - name: password
    key: kv-v2/kubernetes/example
    property: password
  - name: api-key
    key: kv-v2/kubernetes/example
    property: api-key
```
For further validation... I can create a v1 keystore and set kv version to 1 and it works fine. When v1 keystore is set to 2 it actually still shows success and just doesnt put anything in the secret.

Edit: fixed example typo to kvVersion: 2
