### ISSUE TITLE
Consider merging with aws-secret-operator

### ISSUE THREAD

**Issue by max-lobur** [external-secrets/kubernetes-external-secrets#47]
https://github.com/mumoshu/aws-secret-operator is a very similar concept, consider merging two projects.

**Comment by silasbw** [comment]
Doh -- just when you think you've scoured the internet.  Thanks @max-lobur.  Yes, we I agree, we should definitely consider merging.

**Comment by lhotrifork** [comment]
There's also this :) 
https://github.com/ContainerSolutions/externalsecret-operator

**Comment by silasbw** [comment]
....and https://github.com/cmattoon/aws-ssm :)

**Comment by JacopoDaeli** [comment]
Ok ok, but how should we deal with it? What would be the right approach here for considering to merge?

**Comment by reegnz** [comment]
I believe the right approach would be to reach out to these projects and ask them if they want to unify their efforts in a single project.
Maybe open github issues in each of those projects that links to this issue to start a discussion?

**Comment by riccardomc** [comment]
Hi there, and thank you for reaching out!

I am one of the contributors of https://github.com/ContainerSolutions/externalsecret-operator and I think that we would definitely benefit from aligning on a common CRD spec.

We deliberately wanted to keep it simple, so our CRs currently look like this:

```yaml
apiVersion: externalsecret-operator.container-solutions.com/v1alpha1
kind: ExternalSecret
metadata:
  name: example-externalsecret
spec:
  Key: example-externalsecret-key
  Backend: asm-example
```

But it might not be enough for the others?
