### ISSUE TITLE
imagePullSecrets is not correctly added to values.yaml

### ISSUE THREAD

**Issue by balazs-fark-epam** [external-secrets/kubernetes-external-secrets#522]
In https://github.com/godaddy/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/values.yaml
imagePullSecrets is child of image:

```
image:
  repository: godaddy/kubernetes-external-secrets
  tag: 6.0.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []
```

but it templates/deployment.yaml:

it is referenced like

```
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
```
