### ISSUE TITLE
KES Vault misleading errors

### ISSUE THREAD

**Issue by aleksf** [external-secrets/kubernetes-external-secrets#526]
I am testing KES `godaddy/kubernetes-external-secrets:6.0.0` with Vault `Vault v1.5.2 (685fdfa60d607bca069c09d2d52b6958a7a2febd)` on k8s `Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4", GitCommit:"8d8aa39598534325ad77120c120a22b3a990b5ea"`

I got rather strange error messages returned by ES CRD's despite Kubernetes secrets are created and have correct values

The error message is below:
```
kubectl get es -n aleksf-dev-ns
NAME       LAST SYNC   STATUS                                         AGE
rabbitmq   9s          ERROR, invalid role name "kes_kes-demo_role"   66m
redis      4s          ERROR, invalid role name "kes_kes-demo_role"   66m
```

```
(hvac) sysadmin@ansible:~/terraform/tf-vault $ kubectl describe es rabbitmq -n aleksf-dev-ns
Name:         rabbitmq
Namespace:    aleksf-dev-ns
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"kubernetes-client.io/v1","kind":"ExternalSecret","metadata":{"annotations":{},"name":"rabbitmq","namespace":"aleksf-dev-ns"...
API Version:  kubernetes-client.io/v1
Kind:         ExternalSecret
Metadata:
  Creation Timestamp:  2020-10-27T08:45:28Z
  Generation:          2
  Resource Version:    107698256
  Self Link:           /apis/kubernetes-client.io/v1/namespaces/aleksf-dev-ns/externalsecrets/rabbitmq
  UID:                 87d236a2-588b-4394-9664-bff4bb7bf569
Spec:
  Backend Type:  vault
  Data:
    Key:              kes-demo/data/kes/rabbitmq
    Name:             rabbitmq
    Property:         password
  Vault Mount Point:  kubernetes
  Vault Role:         kes_kes-demo_role
Status:
  Last Sync:            2020-10-27T09:53:06.063Z
  Observed Generation:  2
  Status:               ERROR, invalid role name "kes_kes-demo_role"
Events:                 <none>
```

**kes_kes-demo_role** role exists in Vault and is properly configured
```
 / $ vault read  auth/kubernetes/role/kes_kes-demo_role
Key                                 Value
---                                 -----
bound_service_account_names         [kes-kubernetes-external-secrets]
bound_service_account_namespaces    [kube-external-secrets-aleksf]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [kes_policy_kes-demo]
token_ttl                           1h
token_type                          default
```

Vault kubernetes auth backend config is below
```
/ $ vault read auth/kubernetes/config
Key                       Value
---                       -----
disable_iss_validation    true
issuer                    n/a
kubernetes_ca_cert        -----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
kubernetes_host           https://10.43.0.1:443
pem_keys                  []
```

**Comment by aleksf** [comment]
I decided to play around a bit and created new vault role (replica of existing one) 
```
/ $ vault read auth/kubernetes/role/kes
Key                                 Value
---                                 -----
bound_service_account_names         [kes-kubernetes-external-secrets]
bound_service_account_namespaces    [kube-external-secrets-aleksf]
policies                            [kes_policy_kes-demo]
token_bound_cidrs                   []
token_explicit_max_ttl              0s
token_max_ttl                       0s
token_no_default_policy             false
token_num_uses                      0
token_period                        0s
token_policies                      [kes_policy_kes-demo]
token_ttl                           1h
token_type                          default
ttl                                 1h
```
Mapped policy:
```
/ $ vault policy read kes_policy_kes-demo
# allow kes controller to access shared secrets
path "kes-demo/data/kes/*" {
  capabilities = ["read", "list"]
}
```

I created following ES CRD 
```
cat << EOF | kubectl apply -f - -n aleksf-dev-ns
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: blablah 
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: kes	
  data:
  - name: blablah # k8s secret data property name
    key: kes-demo/data/kes/blablah # kv secret path
    property: password # vault kv value name
---
EOF
```

blablah Secret got created and contains value from Vault:
```
(hvac) sysadmin@ansible:~/terraform/tf-vault $ kubectl get secret blablah -n aleksf-dev-ns -o yaml | head
apiVersion: v1
data:
  blablah: YmxhaGJsYWg=
kind: Secret
metadata:
  creationTimestamp: "2020-10-27T10:19:43Z"
  name: blablah
  namespace: aleksf-dev-ns
  ownerReferences:
  - apiVersion: kubernetes-client.io/v1
```

What is even more bizarre is ES resources return "ERROR, 1 error occurred: * permission denied"
```
NAME          LAST SYNC   STATUS                                         AGE
blablah       3s          ERROR, 1 error occurred: * permission denied   4m24s
redis         2s          ERROR, 1 error occurred: * permission denied   13m
springadmin   3s          ERROR, 1 error occurred: * permission denied   6m45s
```

Wondering if it's KES not playing nicely or I am hitting compatibility issues I am not aware of. Most confusing in all of this that secrets are created and values are sync'ed despite CRD error messages.

**Comment by druesendieb** [comment]
We've had a similar problem lately, restarting KES solved our ` ERROR, 1 error occurred: * permission denied` errors, maybe it'll help you as well.

**Comment by aleksf** [comment]
Deleted KES controller Pod - no change

**Comment by arenstar** [comment]
same same ^^ :(

**Comment by Flydiverny** [comment]
Do you get the same errors with 5.2.0?

**Comment by aleksf** [comment]
It turned to be missing trailing slash mistake with `vaultMountPoint` value in the ES CRD 

Below works without producing the error. Interesting despite the error it still worked.

```
spec:
  backendType: vault
  vaultMountPoint: kubernetes/
  vaultRole: kes_kes-demo_role
```

**Comment by aleksf** [comment]
I expressed my optimism too soon apparently. `kubernetes/` is causing problems as now extra trailing slash is appended in the auth request against vault k8s backend `/v1/auth/kubernetes//login` this results in 301 back to `/v1/auth/kubernetes/login`, which then results in 405. 

Changing `vaultMountPoint` back to `kubernetes` works, but we are back with the initial error message

**Comment by arenstar** [comment]
Ok so my issue is now resolved and i have a working vault+external-secrets-manager.

my "ERROR, 1 error occurred: * permission denied" was due to me having used

`http` not 'https` in my kubernetes_host.

the following config worked for me

```
resource "vault_kubernetes_auth_backend_config" "config" {
  backend = vault_auth_backend.kubernetes.path
  kubernetes_host = "https://kubernetes.default.svc.cluster.local:443"
  kubernetes_ca_cert = data.kubernetes_secret.sa.data["ca.crt"]
  token_reviewer_jwt = data.kubernetes_secret.sa.data.token
}
```

**Comment by aleksf** [comment]
Definitely was not an issue here, still got these misleading errors despite everything is syncing properly:

```
status:
  lastSync: "2020-11-17T09:49:54.198Z"
  observedGeneration: 1
  status: ERROR, invalid role name "testrelease-aleksf-dev-kes-role"
```
