### ISSUE TITLE
Retrieving secrets from vault returns in double quotes for kv version 2

### ISSUE THREAD

**Issue by LePhanFF** [external-secrets/kubernetes-external-secrets#541]
Hello,

I have successfully setup vault and Kubernetes

    - name: DATABASE_URL_VAULT
      valueFrom:
        secretKeyRef:
          name: vault-keys
          key: db_url

I am seeing the environment variable returned in double quotes for example: 

DATABASE_URL_VAULT="postgresql://postgres:1233@abc:5432/xyz" was expecting without quotes

DATABASE_URL_VAULT=postgresql://postgres:1233@abc:5432/xyz

Is there a way to make backend-vault.js return secret value without double quotes?

Le

**Comment by mcruzdev** [comment]
@LePhanFF can you help me, please 
I am trying configure Vault with kubernetes locally but it not works.
Do you have an example? I already saw a video on youtube and etc. But I did not get that ;/

**Comment by Flydiverny** [comment]
Please specify KES version used

**Comment by mcruzdev** [comment]
@Flydiverny thank you!

1 - I am using kind (version 0.9.0) to create a cluster Kubernetes 
2 - Set the current cluster context
3 - Create a namespace vault
4 - Install Vault with `helm install vault hashicorp/vault --set "server.dev.enabled=true" --namespace vault`
5 - Create policy app on Vault

```
$ cat <<EOF > /home/vault/app-policy.hcl 
>         path "secret*" {  
>             capabilities = ["read"]
>         }
> EOF

$ vault policy write app /home/vault/app-policy.hcl 
```
6 - Enable Kubernetes Auth
`$ vault auth enable kubernetes`

7 - Write token_reviewer_jwt, kubernetes_host, kubernetes_ca_cert
```
$ vault write auth/kubernetes/config \
token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
8 - Create role for app
```
$ vault write auth/kubernetes/role/myapp \
   bound_service_account_names=app \
   bound_service_account_namespaces=vault \
   policies=basic-app \
   ttl=1h
```
9 - Create secrets
```
$ vault kv put secret/app VAULT_SECRET=username
```

10 - Install Kubernetes-External-Secrets 
``` $ helm install external-secrets/kubernetes-external-secrets ```

11 - my external-secret
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: external-secret-vault
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: myapp
  kvVersion: 1
  data:
  - name: username
    key: secret/app
    property: username

```

When I opened the logs from external-secret-pod i see CONNECTION REFUSED 120.0.0.1:8200/v1/auth/kubernetes/login ;/
