### ISSUE TITLE
Errors when following the kubectl instructions?

### ISSUE THREAD

**Issue by max-sixty** [external-secrets/kubernetes-external-secrets#572]
We don't use helm so I was hoping to generate the manifests and deploy them with `kubectl`.

>If you don't want to install helm on your cluster and just want to use `kubectl` to install `kubernetes-external-secrets`, you could get the `helm` client cli first and then use the following sample command to generate kubernetes manifests:
> ```bash
> $ helm template --output-dir ./output_dir ./charts/kubernetes-external-secrets/
> ```

But when I do that, I get yaml like:

```yaml
# Source: kubernetes-external-secrets/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-kubernetes-external-secrets
```

...and the `RELEASE` prefix isn't a valid k8s name.

Let me know if I'm missing something obvious! Thanks
