### ISSUE TITLE
HashiCorp Vault - Allow secret retrieval from multiple Vault Namespaces

### ISSUE THREAD

**Issue by justinas-b** [external-secrets/kubernetes-external-secrets#584]
Hey,

At the moment, when you deploy KES you can provide `VAULT_NAMESPACE` environment variable which indicates name of Vault namespace from where all secrets will be retrieved, however it is impossible to specify namespace name directly in `ExternalSecret` CRD.

We need to access secrets from multiple namespaces and it would be great to have ability to provide namespace directly in secret definition (`kind: ExternalSecret`), the same way as you can override below env variables:
```
env:
  DEFAULT_VAULT_MOUNT_POINT: "k8s-auth" # optional, default value to be used if not specified in the ExternalSecret
  DEFAULT_VAULT_ROLE: "k8s-auth-role" # optional, default value to be used if not specified in the ExternalSecret
```

with `vaultMountPoint` and `vaultRole`
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-vault-service
spec:
  backendType: vault
  # Your authentication mount point, e.g. "kubernetes"
  # Overrides cluster DEFAULT_VAULT_MOUNT_POINT
  vaultMountPoint: my-kubernetes-vault-mount-point
  # The vault role that will be used to fetch the secrets
  # This role will need to be bound to kubernetes-external-secret's ServiceAccount; see Vault's documentation:
  # https://www.vaultproject.io/docs/auth/kubernetes.html
  # Overrides cluster DEFAULT_VAULT_ROLE
  vaultRole: my-vault-role
...
```

**Comment by Nick-Triller** [comment]
Hi @justinas-b,

just in case this is useful to you: you can remove the VAULT_NAMESPACE environment variable and prefix the Vault path in the ExternalSecret resource with the namespace instead.

Example:
```
spec:
    backendType: vault
    data:
    # Vault namespace = my/namespace, secret in namespace = secrets/data/test
    - key: my/namespace/secrets/data/test
      name: test-secret
      property: my-test-property
```

**Comment by justinas-b** [comment]
Hey @Nick-Triller , is this really possible? If I remove `VAULT_NAMESPACE` environment variable and do as suggested above, 
KES is unable to authenticate with Vault anymore:

```
{"level":30,"time":1614723820844,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"running poll on the secret demo/ns-demo1"}
{"level":20,"time":1614723820855,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"fetching new token from vault for role external-secrets on kubernetes"}
{"level":50,"time":1614723820870,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","payload":{"response":{"statusCode":400,"body":{"errors":["missing client token"]}}},"msg":"failure while polling the secret demo/ns-demo1"}
{"level":20,"time":1614723820870,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"updating status for demo/ns-demo1 to: ERROR, missing client token"}
{"level":20,"time":1614723820884,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"stopping and removing poller 5dd80d7f-c4fc-4578-8475-cb2ed71c49ec"}
{"level":30,"time":1614723820884,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"stopping poller for demo/ns-demo1"}
{"level":20,"time":1614723820884,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"spinning up poller for demo/ns-demo1"}
{"level":30,"time":1614723820884,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"starting poller for demo/ns-demo1"}
{"level":20,"time":1614723820896,"pid":18,"hostname":"kubernetes-external-secrets-97dc94695-fmljv","msg":"next poll for demo/ns-demo1 in 9975 ms"}
```

I have also tried moving `vaultMountPoint` and `vaultRole` from env. variables directly into KES CRD, but it also breaks the stuff with exactly same error as above. What am i missing?

**Comment by Nick-Triller** [comment]
Hi @justinas-b,

If `VAULT_NAMESPACE` is set, KES sets the `X-VAULT-NAMESPACE` header in requests to Vault:
https://github.com/external-secrets/kubernetes-external-secrets/blob/a430320e8b9857154b4eca888fa5775ba3e1cda5/config/index.js#L76-L78
According to the [Vault docs](https://www.vaultproject.io/docs/enterprise/namespaces#usage), the effect of the X-VAULT-NAMESPACE header is simply that all paths are prefixed with the given namespace path.

In my case, the vaultMountPoint is always in the Vault root namespace. KES authenticates with Vault using this single vaultMountPoint and gets a token with a policy that allows accessing specific secrets in other Vault namespaces. This variant works.

I assume each of your Vault namespaces has it's own Kubernetes auth backend.  I haven't tried using multiple vaultMountPoints yet. However, I would expect it to work when the vaultMountPoint is prefixed with the namespace path in the same way the secret must be prefixed with the namespace path if VAULT_NAMESPACE isn't set.

**Comment by justinas-b** [comment]
If i remove `VAULT_NAMESPACE` environment variable and define `vaultMountPoint` directly in `ExternalSecret` CRD, it ignores absolute path and looks only in `root` namespace. It seems that the absolute paths are ignored by KES.

Also, i have tried leaving `VAULT_NAMESPACE` environment variable defined and access the secret in other namespace using full path:
```
spec:
  backendType: vault
  data:
  - key: /dev/shared_namespace/kv/data/demo
    name: xxx
    property: xxx
  kvVesion: 2
  vaultMountPoint: kubernetes
  vaultRole: external-secrets
```

But in this case in vault audit logs i see that it still searches for that secret under the `VAULT_NAMESPACE` instead of root (`VAULT_NAMESPACE=dev/environment`):
"path":"dev/environment/dev/shared_namespace/kv/data/demo"
