### ISSUE TITLE
vault agent support

### ISSUE THREAD

**Issue by jetersen** [external-secrets/kubernetes-external-secrets#590]
Currently the vault backend does not support using the vault agent, which can easily be injected when using vault-helm setup.

**Comment by markgarrigan** [comment]
Valut agent support would be amazing! If anyone can point me in the right direction in the code I can submit a PR.

**Comment by jetersen** [comment]
The simplest is to avoid attempting to fetch a token and simply request the secret directly.

And than with vault agent injection you can use:
```
metadata:
  annotations:
    vault.hashicorp.com/agent-cache-enable: true
    vault.hashicorp.com/agent-cache-use-auto-auth-token: force
    vault.hashicorp.com/agent-cache-listener-port: 8100
```

Than in external-secrets set vault address to sidecar's host and port.
