### ISSUE TITLE
Question: Using AWS Secrets Manager with dockerconfigjson

### ISSUE THREAD

**Issue by blastik** [external-secrets/kubernetes-external-secrets#600]
Hello!

All the closed issues I've seen here regarding the creation of a `type: kubernetes.io/dockerconfigjson` from a `backendType: secretsManager` was by using `Plaintext` AWS secrets instead of `key/value`. Probably due the fact that using `key/value` encapsulates the dockerconfigjson inside another json when the AWS API answers.

My question is: is there any way we could use `key/value` anyway?

Thanks!

**Comment by Flydiverny** [comment]
I believe you can use key value, I think the key has to be the outer most key in the dockerconfig json and the value its value.
In the end the value has to end up on the right format which is how kubernetes wants it, KES just gets it from the backend and puts it in a secret! No special magic for dockerconfigs.

**Comment by blastik** [comment]
> I believe you can use key value, I think the key has to be the outer most key in the dockerconfig json and the value its value.
> In the end the value has to end up on the right format which is how kubernetes wants it, KES just gets it from the backend and puts it in a secret! No special magic for dockerconfigs.

ok so here is my secret value in aws (key is DOCKER_CONFIG):

```
{"auths":{"whatever.jfrog.io":{"username":"kubernetes","password":"whatever","email":"whatever@whatever.com"}}}
```

and here is the external secret definition 

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: regcred
spec:
  backendType: secretsManager
  roleArn: {{ include "secrets.roleArn" . }}
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ include "secrets.regcred_name" . }}
      name: DOCKER_CONFIG
```

creation fails with:

`ERROR, Secret "regcred" is invalid: data[.dockerconfigjson]: Required value`

**Comment by Flydiverny** [comment]
Name must be set to `.dockerconfigjson` as this is what `type: kubernetes.io/dockerconfigjson` must have.

This would probably work
```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: regcred
spec:
  backendType: secretsManager
  roleArn: {{ include "secrets.roleArn" . }}
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - key: {{ include "secrets.regcred_name" . }}
      name: ".dockerconfigjson"
      property: DOCKER_CONFIG
 ```
