### ISSUE TITLE
Unable to use AWS KMS CMK

### ISSUE THREAD

**Issue by argais** [external-secrets/kubernetes-external-secrets#627]
We've been successfully using external secrets for months (amazing piece of software, thanks for your work!), but recently started moving our ssm parameter store secure strings to using a CMK.

We're using IRSA to give the pod permissions, and with the aws/ssm key (standard one) everything works perfectly.

We created a CMK and updated the role policy to:

```
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": ["kms:*","ssm:*"],
            "Resource": "*"
        }
```
So, basically, full ssm and kms access, but we're still getting a permission error.

```
│   Status:               ERROR, The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access. (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 3ee54ab1-2f1b-4d9d-8735-e46987cb5355; Proxy: null)                  │
```

To rule out issues with the IRSA, we spinned up an alpine pod with aws cli using the same role and we can read the parameter just fine.

The ext secret yaml
```
apiVersion: kubernetes-client.io/v1                                                                                                                       
kind: ExternalSecret                                                                                                                                      
metadata:                                                                                                                                                 
  name: test                                                                                                                                     
  namespace: app-test                                                                                                                             
spec:                                                                                                                                                     
  backendType: systemManager                                                                                                                              
  data:                                                                                                                                                   
  - key: /secret/test                                                                                                                    
    name: test
```

Any ideas on how to get this going?
Also tried adding region to the ext secret yaml, no dice :/ 

Using the latest version of ext secrets deployed from the latest helm chart as of today.
