### ISSUE TITLE
Feature request: Recursive mode in other backends like in SSM Parameter Store

### ISSUE THREAD

**Issue by KIVagant** [external-secrets/kubernetes-external-secrets#632]
Hi! I am planning to migrate some custom-made solution to the K8s External Secrets, which looks awesome (thank you all for the work). I have two primary features in the legacy solution:
- ability to load all secrets from a desired "namespace" (path) in a secret storage;
- ability to mutate secrets on the fly using a simple templater (like variable substitutions);

While the second feature is kind of rare, the first one is important. The conception of the project is nice but it requires us to maintain the mapping between a backend storage and the `ExternalSecret` object in Kubernetes. Which means that any time when a developer adds or changes a key in the backend storage, someone or something should synchronize the keys in the `ExternalSecret` objects. Which in its turn requires us to still have additional piece of software to perform this automatic synchronization. This problem can be (as I believe) easily solved with `AWS SSM Parameter Store` which is shown in the example from [the docs](https://github.com/external-secrets/kubernetes-external-secrets#aws-ssm-parameter-store):

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: hello-service
spec:
  backendType: systemManager
  data:
    - path: /extra-people/
      recursive: true
```

**If** I understand this correctly, all keys from `/extra-people/` path will be converted into a regular Kubernetes Secret (or will there be many of them?). And than in a Kubernetes **Deployment**, we can do something like this:

```yaml
spec:
  containers:
    envFrom:
    - secretRef:
        name: hello-service
        optional: true
```

...which will magically inject all available secrets from **SSM Parameter Store** into a **Pod** produced by the **Deployment** without having to explicitly mention each of them.

So the **feature request**: can the `recursive` feature be added for other backends like **Hashicorp Vault** and **AWS Secret Manager**?
