### ISSUE TITLE
Helm chart install problems: User cannot watch resource "namespaces" in API group "kubernetes-client.io" in the namespace "externalsecrets"

### ISSUE THREAD

**Issue by sklarsa** [external-secrets/kubernetes-external-secrets#634]
I'm trying to install kubernetes-external-secrets on a `k3d` cluster to experiment with, but I'm running into this issue and I'm not sure how to resolve it.

My environment is:
Helm v3.5.2
kubernetes-external-secrets v6.3.0
k3d v 4.2.0

The command I ran is:
```bash
$ helm install kubernetes-external-secrets external-secrets/kubernetes-external-secrets --skip-crds --set env.VAULT_ADDR=$VAULT_ADDR
```

The pod starts up, but I continually get this error message in the logs:
```
"namespaces.kubernetes-client.io \"externalsecrets\" is forbidden: User \"system:serviceaccount:default:kubernetes-external-secrets\" cannot watch resource \"namespaces\" in API group \"kubernetes-client.io\" in the namespace \"externalsecrets\""
```

The only modification I made to the serviceaccount is adding a ClusterRoleBinding to the token reviewer role to enable k8s vault auth:
```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-external-secrets-tokenreview-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: kubernetes-external-secrets
  namespace: default
```

I'm fairly new to k8s, so I apologize in advance if this has been asked before

**Comment by gilly42** [comment]
same problem here (except i didnt make the modification). 
helm Version: v3.5.2
kubernetes-external-secrets v6.3.0
k8s: v1.20.2+k3s1

**Comment by skuffe** [comment]
I am seeing the same issue,

I believe [this](https://github.com/external-secrets/kubernetes-external-secrets/commit/85739fde531e64eb329cc4a28264ffc80e29a5f0) is the commit thats responsible. Not 100% sure why its ocurring, but its definitely related to the namespacing.

if you define env.WATCHED_NAMESPACES with a specific namespace, then the controller actually works, but obviously that is not ideal, if the desired behavior is to watch all namepaces.

**Comment by onedr0p** [comment]
Same problem here, I have to downgrade to 6.1.0 in order for it to work without declaring namespaces in the config.

**Comment by Flydiverny** [comment]
Cannot reproduce this in kind and k3s is not supported on WSL2 :[
I'm thinking this is an issue related to k3s unless someone here has run into this without using k3s?

**Comment by onedr0p** [comment]
> Cannot reproduce this in kind and k3s is not supported on WSL2 :[

Did you try k3d (k3s in Docker)?

**Comment by Flydiverny** [comment]
Right, of course 😅 
Can reproduce in k3d indeed.
Fixing the permission could be done with 

Setting this in values.yaml
```
customClusterRoles:
  - apiGroups: ["kubernetes-client.io"]
    resources: ["namespaces"]
    verbs: ["watch"]
```

However this will still cause a loop of the watch stream dying and restarting infinitely.
Not sure why this happens in k3s but not others.
Made some changes in #673 which avoids the namespace api if not watching a specific namespace.
You can try it out from `ghcr.io/external-secrets/kes-dev:pr-673`
