### ISSUE TITLE
Vault kv v1 issue: "Failed to JSON.parse value for 'secret/path', please verify that your secret value is correctly formatted as JSON..."

### ISSUE THREAD

**Issue by sklarsa** [external-secrets/kubernetes-external-secrets#643]
As referenced in [another ticket](https://github.com/external-secrets/kubernetes-external-secrets/issues/630#issuecomment-786051315), I'm hitting an issue when using vault kv v1:

`Failed to JSON.parse value for 'kv/data/hello-service/credentials', please verify that your secret value is correctly formatted as JSON. To use plain text secret remove the 'property: password'`

Environment
-------------
kubernetes-external-secrets v6.1.0
vault 1.6.2

external-secret.yaml
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: hello-vault-service
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: demo
  data:
  - name: passwordv1
    key: kv/data/hello-service/credentials
    property: password
  - name: api-keyv1
    key: kv/data/hello-service/credentials
    property: api-key
```

Detail
------

This seems like a problem that the application is not properly recognizing vault kv v1 secrets, and is treating them as v2.  I added the following debugging line to `vault-backend.js` under `const secretResponse = await client.read(key)`
```
this._logger.info(`kvVersion ${kvVersion}`)
```
and received the following output:
```
{"level":30,"time":1614279814580,"pid":435,"hostname":"k3d-app-server-0","msg":"kvVersion 2"}
```

The secret does get created, it's just empty
```
$ k describe secret hello-vault-service
Name:         hello-vault-service
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  Opaque

Data
====
```
