### ISSUE TITLE
Failure while polling the secret: could not load backend configuration

### ISSUE THREAD

**Issue by andrexus** [external-secrets/kubernetes-external-secrets#649]
I installed the Helm Chart on my cluster with the following values.yaml

```bash
helm upgrade external-secrets --namespace=infrastructure --install -f ./values.yaml external-secrets/kubernetes-external-secrets
```
values.yaml
```yaml
env:
  WATCHED_NAMESPACES: "infrastructure,ns1,ns2"
  VAULT_ADDR: http://vault:8200
  DEFAULT_VAULT_MOUNT_POINT: "kubernetes"
  DEFAULT_VAULT_ROLE: "kubernetes-external-secrets"

serviceAccount:
  name: external-secrets
```

Then I created an ExternalSecret
```yaml
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: mysecret
  namespace: infrastructure
spec:
  backendType: vault
  dataFrom:
    - secret/data/mysecret
```

In logs I can see the following messages

```bash
{"level":30,"time":1614862357557,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-5ffb879c7c-tkq58","msg":"running poll on the secret infrastructure/mysecret"}
{"level":50,"time":1614862357582,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-5ffb879c7c-tkq58","payload":{"response":{"statusCode":500,"body":{"errors":["could not load backend configuration"]}}},"msg":"failure while polling the secret infrastructure/mysecret"}
{"level":30,"time":1614862357596,"pid":19,"hostname":"external-secrets-kubernetes-external-secrets-5ffb879c7c-tkq58","msg":"stopping poller for infrastructure/mysecret"}
```

External secrets version: kubernetes-external-secrets@6.4.0
Vault version: 1.6.2
