### ISSUE TITLE
Template section was not rendered.

### ISSUE THREAD

**Issue by yusaito04** [external-secrets/kubernetes-external-secrets#650]
I'm trying to get secrets from `gcpSecretManager` and convert them to kubernetes.io/dockerconfigjson using `lodash.template`.
I applied code below, but it didn't work.

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: ips-test-imagepullsecret
spec:
  backendType: gcpSecretsManager
  projectId: our-gcp-project
  data:
    - key: ips-test-cr-id
      name: crid
    - key: ips-test-cr-secret
      name: crsecret
    - key: ips-test-server
      name: crserver
  template:
    stringData: # I used stringData instead of data because this is test code.
      .dockerconfigjsontest: |
        <%= Buffer.from("{\"auths\":{\"" + data.crserver + "\":{\"auth\":\"" + Buffer.from(data.crid + ":" + data.crsecret).toString("Base64") + "\"}}}").toString("Base64") %>
```

```
$ kubectl get secret/ips-test-imagepullsecret -n ips-test -ogo-template='{{ index .data ".dockerconfigjsontest" | base64decode }}'
<%= Buffer.from("{\"auths\":{\"" + data.crserver + "\":{\"auth\":\"" + Buffer.from(data.crid + ":" + data.crsecret).toString("Base64") + "\"}}}").toString("Base64") %>
$
```

It seems that template was not rendered. I read template section of README.md many time but I couldn't understand why it does not work.
Could you help me for this problem?

Our environment is blow.
* backend: gcpSecretManager
* cluster: gke 1.18.12-gke.1210
* kubernetes-external-secret: v6.0.0
