### ISSUE TITLE
Recreate content of Vault in k8s

### ISSUE THREAD

**Issue by j-zimnowoda** [external-secrets/kubernetes-external-secrets#653]
I was wondering if KES could recreate content of HashiCorp Vault.

Assuming that a Vault user follow some convention in defining paths, e.g.:
```
 /secrets/data/k8s/<namespace>/<secret-type>/<secret-name>
```
we could automate a lot of work and minimise hassle of repeating ourselves while defining `ExternalSecret` CRs.

KES cloud recognise path pattern and automatically recreate k8s secrets at a given namespace.

E.g.:
```
 /secrets/data/k8s/team1/generic/abc
```
with keys: `aa`, `bb`

would result in:
```
apiVersion: v1
data:
  aa: c29tZSBzZWNyZXQgMQo=
  bb: c29tZSBzZWNyZXQgMgo=
kind: Secret
metadata:
  name: abc
  namespace: team1
type: Opaque
```

What do you think about that?
