### ISSUE TITLE
Clusterrole default for `customresourcedefinitions` is unchecked after running `helm repo update`

### ISSUE THREAD

**Issue by ashwanth1109** [external-secrets/kubernetes-external-secrets#695]
I recently uninstalled `external-secrets` on my eks cluster and tried to install again with the following command:
```
helm install external-secret-sync external-secrets/kubernetes-external-secrets -f external-secret-chart-values.yml
```

The `external-secret-chart-values.yaml` is as below:
```
# Environment variables to set on deployment pod
env:
  AWS_REGION: us-east-1
  POLLER_INTERVAL_MILLISECONDS: 300000
  LOG_LEVEL: info
  METRICS_PORT: 3001
  VAULT_ADDR: http://127.0.0.1:8200

# Create environment variables from existing k8s secrets
envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: external-secret-sync
    key: AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: external-secret-sync
    key: AWS_SECRET_ACCESS_KEY

rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Specifies annotations for this service account
  annotations: {}

replicaCount: 1

image:
  repository: godaddy/kubernetes-external-secrets
  tag: 3.1.0
  pullPolicy: IfNotPresent
  imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

securityContext:
  runAsNonRoot: true
  runAsUser: 999

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

serviceMonitor:
  enabled: false
  interval: "30s"
  namespace:
```

When I tried to install I got the following error:
```
Error: failed to download "external-secrets/kubernetes-external-secrets" (hint: running `helm repo update` may help)
```

Ran `helm repo update`:
```
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "external-secrets" chart repository
Update Complete. ⎈Happy Helming!⎈
```

The clusterrole that is created after this has `CREATE` disabled by default for `customresourcedefinitions`. I would like to enable this and I'm not sure how to do this. Kindly help me understand what changes are required here.

**Comment by Flydiverny** [comment]
I think that you want to specify a `--version` flag to your helm install command with an earlier version of the chart, as the latest chart (which you end up using) has breaking changes compared to the version you are running (3.1.0).
So to get the chart which was released with version 3.1.0 you should be able to do

```
helm install external-secret-sync external-secrets/kubernetes-external-secrets --version 3.1.0 -f external-secret-chart-values.yml
```

**Comment by ashwanth1109** [comment]
@Flydiverny , thanks for the response. 🙇🏾‍♂️ 
I was able to fix my issue by explicitly setting the rbac rules for `customresourcedefinitions` as follows:
```
customClusterRoles:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    resourceNames: [ "externalsecrets.kubernetes-client.io" ]
    verbs: [ "get", "create", "update" ]
```

Reference code:
https://github.com/external-secrets/kubernetes-external-secrets/blob/095af78e7bd9ab0bb52b4a171f03f604ad9e4f42/charts/kubernetes-external-secrets/templates/rbac.yaml
