### ISSUE TITLE
With AWS Secrets Manager backend, make one AWS API call per secret even when not using dataFrom

### ISSUE THREAD

**Issue by mbonica1990** [external-secrets/kubernetes-external-secrets#704]
I'm using secretsManager as my backend for some k8s secrets; my ExternalSecret object looks a bit like this.

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  backendType: secretsManager
  data:
    - key: /path/to/secret
      name: username
      property: username
    - key: /path/to/secret
      name: password
      property: password`
```
      
  Notice that I have one Secrets Manager secret, called `/path/to/secret`, that I'm getting two values from (`username` and `password`) and surfacing as two different pieces of data in my secret.
  
 This works, but I can see through CloudTrail that the External Secrets pod makes `two` API requests to Secrets Manager (one per item in the `data` list). I'm wondering if there's a way to get I can make it get both values in just `one` API call, since I imagine the response it's getting from the first call also has the values needed for the second. I'd like to minimize the number of API calls I make to AWS to avoid getting throttled.
 
 I understand that `dataFrom` would solve my problem, but I'm hoping to avoid using that if I can; we'd like to be explicit about what secrets we're including in our applications, and `dataFrom` doesn't make it clear when looking at the YAML which values I'm bringing into my application. (If there's a way to make `dataFrom` only import a subset of a secret, that would work for me too.)
 
 I was just wondering if this is something that I can achieve, or if it's a reasonable ask.

**Comment by Flydiverny** [comment]
There is no support for this in the implementation.
While it could be implemented somewhat simply for the base case.
It grows in complexity when you get things like:

```yaml
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  backendType: secretsManager
  data:
    - key: /path/to/secret
      name: username
      property: username
      versionStage: AWSPREVIOUS
    - key: /path/to/secret
      name: credentials
      isBinary: true
```

Where the secret is the same but maybe one uses an earlier version or one other individual configurations.
