### ISSUE TITLE
PSA: k8s 1.21 Vault Service Account Issuer

### ISSUE THREAD

**Issue by dirtycajunrice** [external-secrets/kubernetes-external-secrets#721]
Looks like there are a few people running into the `ISS claim invalid` when bumping to 1.21.

Starting k8s v1.21, [Service Account Issuer Discovery](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-issuer-discovery) feature gate is now stable and enabled by default. You have 2 methods of resolving the issue.

### Secure 
Configure your cluster to securely serve validation. I there are too many unique environments to give an appropriate configuration example, but [banzai cloud](https://banzaicloud.com/blog/kubernetes-oidc/) has a nice writeup to get you started.
### Insecure
If you want to continue using kubernetes-external-secrets the prior way, you need to [disable issuer validation](https://www.vaultproject.io/api/auth/kubernetes#disable_iss_validation).
CLI Example
```
$ vault write auth/kubernetes/config \
        token_reviewer_jwt="$SA_JWT_TOKEN" \
        kubernetes_host="$K8S_HOST" \
        kubernetes_ca_cert="$SA_CA_CRT" \
        disable_iss_validation=true
```

**Comment by moolen** [comment]
Hej @DirtyCajunRice, thanks for reporting, i've pinned this issue!

**Comment by laukaichung** [comment]
I'm using Bank Vaults and facing the same problem. Have to disable ISS claim validation.

**Comment by CodeGlitcher** [comment]
Same problem,
Will there be a fix or do we need to migrate to the generic jwt auth method?

**Comment by rdavyd** [comment]
Fixed the problem by explicitly configuring JWT issuer for the vault like this (rest of arguments are from vault documentation):
```
vault write auth/kubernetes/config issuer="https://kubernetes.default.svc.my.nice.cluster.local" token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
Alternatively that may be set via UI.
Issuer name `https://kubernetes.default.svc.my.nice.cluster.local` can be looked up in kube-apiserver arguments on master.

**Comment by adelca** [comment]
It would be nice to specify from what version of Vault "_disable_iss_validation=true_" is supported. I can see here it was added in June 2020:
https://github.com/hashicorp/vault/pull/9142
People using Vault versions older than June 2020 wont be able to use this workaround.

**Comment by samvdb** [comment]
For anyone still bumping into this issue, ensure `kubernetes_host` has a scheme and port defined ( eg http://vault:8200 ).

To get authentication working without enabling `disable_iss_validation`, manually create a service account, secret and mount it in the pod.

Example:

The service account:
```yaml
---
apiVersion: v1
automountServiceAccountToken: false
kind: ServiceAccount
metadata:
    name: secret-sa
    namespace: example
```

The secret:
```yaml
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
   name: sa-token
   annotations:
      kubernetes.io/service-account-name: secret-sa
```
Modify helm chart:

values.yaml
```yaml
serviceAccount:
  create: false
  name: secret-sa

filesFromSecret:
   sa-secret:
     secret: sa-token
     mountPath: /var/run/secrets/kubernetes.io/serviceaccount
```

This will create a fixed token in the secret `sa-token` which is then mounted into the pod on `/var/run/secrets/kubernetes.io/serviceaccount`.

Note that if you do not create your own service account secret, a fresh token will be requested from the kube-api server through the use of projected volumes. This token is NOT stored in a secret. This can be confusing when troubleshooting.
