### ISSUE TITLE
When using spec.template I get the data elements as keys as well as the output from the template 

### ISSUE THREAD

**Issue by ErikLundJensen** [external-secrets/kubernetes-external-secrets#750]
When I create an ExternalSecret with a temple:

```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  backendType: azureKeyVault
  keyVaultName: my-vault
  data:
    - key: "my-special-key"
      name: mykey
  template:
    stringData:
      settings.yaml: |
        aKey: "<%= data.myKey %>"
```

then the result is a secret that contains:
```
data:
  settings.yaml: |
    aKey: SGkK
  mykey: SGkK
```

This breaks the use of projected secrets in Deployment volumes as we will end up with 2 files (settings.yaml and mykey)
I would like to get the output from the template only in the secret. Is that somehow possible?

**Comment by ErikLundJensen** [comment]
Work-a-round was to specify item in the Deployment:
```
      volumes:
      - name: config
        projected:
          sources:
          - secret:
              name: my-secret
              items:
              - key: "settings.yaml"
                path: "settings.yaml"
```
