### ISSUE TITLE
--env-file equivalent for external secret

### ISSUE THREAD

**Issue by vpsheretanzu** [external-secrets/kubernetes-external-secrets#752]
I have file "envs" with multiple data such as myapp-password, myapp-db, myapp-token and I am creating secret using --from-env-file which will create secret my-app:

envs
```
myapp-password=password
myapp-db="Data Source=mssql; User Id=admin; Password=supersecret;"
myapp-token=abcdef
```
---
 `kubectl create secret generic my-app --from-env-file=envs -o yaml`

```
apiVersion: v1
data:
  myapp-db: IkRhdGEgU291cmNlPW1zc3FsOyBVc2VyIElkPWFkbWluOyBQYXNzd29yZD1zdXBlcnNlY3JldDsi
  myapp-password: cGFzc3dvcmQ=
  myapp-token: YWJjZGVm
kind: Secret
metadata:
type: Opaque
```

I can pass file envs using --from-env-file and create data within the secret:

Is there an equivalent for the kind: ExternalSecret, so that I do not have to create separate aws secret for each data?
