### ISSUE TITLE
CRD empty properties breaking intellij parsing (cause of empty properties)

### ISSUE THREAD

**Issue by joggeli34** [external-secrets/kubernetes-external-secrets#753]
Hi,

When including the CRD for parsing in the intellij, it breaks parsing as the CRD is having empty properties which are not supported there in openApiSchema.

The parsing will be fixed to not break in the intellij following the issue:
https://youtrack.jetbrains.com/issue/IDEA-269698

Probably the empty properties could just be omitted? (I don't know openApi well enough)
```yaml
                    oneOf:
                      - properties:
                          key:
                          name:
                          property:
                          isBinary:
                          secretType:
                        required:
                          - key
                          - name
                      - properties:
                          path:
                          recursive:
                        required:
                          - path
```
