### ISSUE TITLE
ERROR, The security token included in the request is invalid.

### ISSUE THREAD

**Issue by wiharto** [external-secrets/kubernetes-external-secrets#772]
I had the same issue as below previously:
https://github.com/external-secrets/kubernetes-external-secrets/issues/749
But, managed to get a different error, which is 
`ERROR, The security token included in the request is invalid.`
after I did below.

**Setup:**
k8s cluster on EC2 instance.
I setup my k8s secret using below
`kubectl create secret generic aws-credentials \
--from-literal=aws_access_key_id=xxx \
--from-literal=aws_secret_access_key=xxx \
--from-literal=aws_session_token=xxx`

**My values.yaml**

```
env:
    AWS_REGION: us-east-1
   AWS_DEFAULT_REGION: us-east-1

envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: aws-credentials
    key: aws_access_key_id
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: aws-credentials
    key: aws_secret_access_key
```

**I installed externalsecrets using:**
`helm install external-secrets-release external-secrets/kubernetes-external-secrets -f values.yaml`

**My externalsecret.yaml**
```
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: es-test
spec:
  backendType: secretsManager
  data:
    - key: test_user_5
      name: test_user_5_username
      property: username
    - key: test_user_5
      name: test_user_5_password
      property: password
```
