### ISSUE TITLE
how to define service account annotations in values file

### ISSUE THREAD

**Issue by vpsheretanzu** [external-secrets/kubernetes-external-secrets#779]
values.yaml file content
annotations:
  "eks.amazonaws.com/role-arn":'arn:aws:iam::1111111:role/k8s-external-secrets'

I am getting following error:-

Error: failed to parse values.yaml: error converting YAML to JSON: yaml: line 118: did not find expected key

**Comment by Flydiverny** [comment]
Should be under serviceAccount.annotations, double check the indentation

https://github.com/external-secrets/kubernetes-external-secrets/blob/2e00799017a804447a39ca64fc98b8b54740c618/charts/kubernetes-external-secrets/values.yaml#L114-L118

**Comment by didlawowo** [comment]
this section doesn't work 

```
  annotations: 
    iam.gke.io/gcp-service-account: cluster-sa@gke2-318614.iam.gserviceaccount.com
  

```
in template it work,
` helm template charts/kubernetes-external-secrets/ -f values/external-secret.yaml | grep -6  cluster
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-kubernetes-external-secrets
  namespace: "kube-infra"
  annotations: 
    iam.gke.io/gcp-service-account: cluster-sa@gke2-318614.iam.gserviceaccount.com
  labels:
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.2.2
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
---`

but on account nothing.

```
metadata:
  annotations:
    meta.helm.sh/release-name: esm
    meta.helm.sh/release-namespace: kube-infra
  creationTimestamp: "2021-08-13T09:58:06Z"
  labels:
    app.kubernetes.io/instance: esm
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubernetes-external-secrets
    helm.sh/chart: kubernetes-external-secrets-8.2.3
  name: esm-kubernetes-external-secrets
  namespace: kube-infra
```
