### ISSUE TITLE
Error trying to pull binary secret from AWS Secrets Manager

### ISSUE THREAD

**Issue by ap13istream** [external-secrets/kubernetes-external-secrets#807]
Using kubernetes-external-secrets v6.4.0
The feature seems to be implemented in version 6.1.0

Error message: 
```
"Failed to JSON.parse value for 'test-binary-secret', please verify that your secret value is correctly formatted as JSON."}
```
Secret when pulled from AWS Secrets Manager with AWS CLI (the values are redacted for security)
```
{
    "ARN": "arn:aws:secretsmanager:us-west-2:REDACTED",
    "Name": "test-binary-secret",
    "VersionId": "REDACTED",
    "SecretBinary": "BASE64ENCODEDVALUE",
    "VersionStages": [
        "AWSCURRENT"
    ],
    "CreatedDate": "2021-07-27T17:09:06.066000-07:00"
}
```
externalsecret.yaml
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test-binary-secret
  namespace: pub
spec:
  backendType: secretsManager
  dataFrom:
    - cluster-name/test-binary-secret

```

**Comment by ap13istream** [comment]
Resolved by updating externalsecret.yaml to 
```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test-binary-secret
  namespace: pub
spec:
  backendType: secretsManager
  data:
    - key: cluster-name/test-binary-secret
      name: test-binary-secret
    
```
