### ISSUE TITLE
AccessDeniedException when using non default encryption key in AWS Secret Manager

### ISSUE THREAD

**Issue by impicklejon** [external-secrets/kubernetes-external-secrets#838]
When trying to retrieve secrets encrypted with non default key:
```
      message: "could not get secret data from provider: key \"XXX\"
        from ExternalSecret \"XXX\": AccessDeniedException:
        Access to KMS is not allowed\n\tstatus code: 400, "
      reason: SecretSyncedError
      status: "False"
      type: Ready
```
    
Works with the same secret in the same account if encrypted with DefaultEncryptionKey

```
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: XXXX
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: XXXXX
      property: XXXX
    secretKey: XXX
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: XX
  target:
    creationPolicy: Owner
    name: XX
```
