### ISSUE TITLE
Excluding original data from templated secret

### ISSUE THREAD

**Issue by Amet13** [external-secrets/kubernetes-external-secrets#848]
Hey.
Is it possible to exclude source data from generated certificate?

I'm using this templating:
```
---
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: microservices-repo
  namespace: argo-cd
spec:
  backendType: secretsManager
  data:
    - key: devops-kubernetes-secrets
      name: GITHUB_ORG_TOKEN
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repository
    stringData:
      url: |
        https://github.com/lalala
      type: |
        git
      password: |
        <%= JSON.parse(data.GITHUB_ORG_TOKEN).GITHUB_ORG_TOKEN %>
```

I **expect** to get a secret like:
```
apiVersion: v1
data:
  password: somebase64=
  type: somebase64==
  url: somebase64==
kind: Secret
metadata:
  name: microservices-repo
```

But I'm getting:
```
apiVersion: v1
data:
  GITHUB_ORG_TOKEN: somebase64=
  password: somebase64=
  type: somebase64==
  url: somebase64==
kind: Secret
metadata:
  name: microservices-repo
```

Wanna exclude this one `GITHUB_ORG_TOKEN`, but didn't find any docs about it
