### ISSUE TITLE
no handler for route 

### ISSUE THREAD

**Issue by lincate** [external-secrets/kubernetes-external-secrets#857]
**Environment:**
K8S: 1.22.1
vault: 1.8.3
kubernetes-external-secrets: 8.3.2

Define a ES as below:
```
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: vault-kv1
  namespace: vault
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: webapp
  kvVersion: 2
  dataFrom:
    - kv/data/demo-app/user01
```

But get no handler for route `'kv/data/demo-app/user01'`.
When I use Vault CLI as :` vault kv get demo-app/user01`
I can get correct response from vault.

Full log content as below:
`"payload":{"response":{"statusCode":404,"body":{"errors":["no handler for route 'kv/data/demo-app/user01'"]}}},"msg":"failure while polling the secret vault/vault-kv1"}`

Anyone can help to handler this issue?
