### ISSUE TITLE
Inaccessible host: `secretsmanager.us-east-1.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.

### ISSUE THREAD

**Issue by morriq** [external-secrets/kubernetes-external-secrets#874]
Hello

I got error after defining simple secret

```yaml
      apiVersion: 'kubernetes-client.io/v1'
      kind: ExternalSecret
      metadata:
        name: cloudflare-secret
        namespace: default
      spec:
        backendType: secretsManager
        data:
          - key: home-cluster
            property: CLOUDFLARE_API_TOKEN
            name: CF_API_TOKEN
```

it prints

> Inaccessible host: `secretsmanager.us-east-1.amazonaws.com' at port `undefined'. This service may not be available in the `us-east-1' region.

I tried many regions and many versions of external secrets. Now I'm using latest (8.4.0)

Could somebody please help me with that?
