### ISSUE TITLE
IBM-Cloud-Secret-Manager Arbitrary secret creating with wrong indentation 

### ISSUE THREAD

**Issue by chokhareganesh** [external-secrets/kubernetes-external-secrets#878]
Hi Team,
I have followed [https://github.com/ibm-cloud-docs/secrets-manager/blob/9d95ea9a8a94dbab7ce40fc56775fa277ccbe3c3/tutorials/kubernetes-secrets.md]( https://github.com/ibm-cloud-docs/secrets-manager/blob/9d95ea9a8a94dbab7ce40fc56775fa277ccbe3c3/tutorials/kubernetes-secrets.md)
for integrating secret with Kubernetes cluster,

I have created a secret type as **Arbitrary secret** but when I access this secret inside K8S cluster its not preserving secret indentation/format

1. secret I have created **Arbitrary secret** inside **secret-manager** (YAML object)

```
route:
  receiver: "watchdog"
  group_by: [ 'alertname', 'cluster', 'service' ]
  routes:
    - match:
        alertname: Watchdog
      receiver: "watchdog"
    - receiver: "slack_pagerduty"
receivers:
  - name: watchdog
  - name: slack_pagerduty
    slack_configs:
      - channel: #test
        api_url: https://hooks.slack.com/
        title: "{{ range .Alerts }}{{ .Annotations.summary }}\n{{ end }}"
        text: "{{ range .Alerts }}{{ .Annotations.description }}\n{{ end }}"
        send_resolved: true
    pagerduty_configs:
      - service_key: test-pager-key
```
2. I have created external secret for above object inside K8s cluster
3. The secret will look like as 
```
{"payload":"route:\n  receiver: \"watchdog\"\n  group_by: [ 'alertname', 'cluster', 'service' ]\n  routes:\n    - match:\n        alertname: Watchdog\n      receiver: \"watchdog\"\n    - receiver: \"slack_pagerduty\"\nreceivers:\n  - name: watchdog\n  - name: slack_pagerduty\n    slack_configs:\n      - channel: #test\n        api_url: https://hooks.slack.com/\n        title: \"{{ range .Alerts }}{{ .Annotations.summary }}\\n{{ end }}\"\n        text: \"{{ range .Alerts }}{{ .Annotations.description }}\\n{{ end }}\"\n        send_resolved: true\n    pagerduty_configs:\n      - service_key: test-pager-key"}
```
---
## **questions:**
1. why its created as json rater than yaml ? it not make any sense as it converting to json
2. If I want to store as YAML how to use secrete manager for YAML configuration file ?  I want to create exact same secret with same value which I stored inside Secret-Manager

**Comment by chokhareganesh** [comment]
Hi @Flydiverny we need your help here, Thanks

**Comment by philippselle** [comment]
Hi @chokhareganesh 
If you use external secret as follows:

```
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: arbitrary-secret
spec:
  backendType: ibmcloudSecretsManager
  data:
    - key: <secret-id>
      name: file
      property: payload
      secretType: arbitrary
```

You will get a secret, which contains your `yaml` input (even with the same indentation).
