### ISSUE TITLE
ERROR, Invalid character in header content ["Authorization"] in new installation of kubernetes-external-secrets

### ISSUE THREAD

**Issue by sufyanadam** [external-secrets/kubernetes-external-secrets#912]
Following [this](https://thenewstack.io/managing-kubernetes-secrets-with-aws-secrets-manager/) guide. Was able to successfully get it working last year in November.

Following the same steps on a new cluster and a brand new installation of kubernetes-external-secrets helm chart, getting the error `ERROR, Invalid character in header content ["Authorization"]`.  Downgrading to version `8.4.0` (last known working version) made no difference. The AWS SDK has been updated recently, perhaps there is an issue with that? Is anybody else having the same issue?

My values file:
```
env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

envVarsFromSecret:
  AWS_ACCESS_KEY_ID:
    secretKeyRef: "aws-credentials"
    key: "id"
  AWS_SECRET_ACCESS_KEY:
    secretKeyRef: "aws-credentials"
    key: "key"
```
